Django_part/Django_part/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    #url(r'index/', include('one.urls')),
    url(r'^one/', include('one.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

Django_part/one/urls.py
__author__ = 'например Андрей'
from django.conf.urls import url

from . import views

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.index_view.as_view(), name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^predictions/about/$', views.about, name='about_from_predict'),
    url(r'^predict_search/$', views.predict_search, name='predictS'),#Перерделать, по возможности, на более гибкую ссылку
    url(r'^test/$', views.test, name='test'),
    url(r'^predictions/$', views.predict_view.as_view(), name='predict'),
    url(r'^strategy/$', views.strategy, name='strategy'),
    url(r'^variants/$', views.variants, name='variants'),
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

Django_part/one/models.py
from django.db import models
# Create your models here.


class Player(models.Model):
    GUID = models.CharField(max_length=36)
    name = models.CharField(max_length=100)
    total_games = models.CharField(max_length=3)
    win_rate = models.CharField(max_length=7)
    svoi_podachi = models.CharField(max_length=9)
    chuz_podachi = models.CharField(max_length=9)
    set_rate = models.CharField(max_length=7)
    game_rate = models.CharField(max_length=7)
    break_point = models.CharField(max_length=9)

    def finder(name):
        return Player.name == name
        # def __str__(self):
        #   return self.TotalGames


class Game(models.Model):
    GUID = models.CharField(max_length=36)
    tournament = models.CharField(max_length=100)
    time = models.DateTimeField(max_length=30)
    players = models.CharField(max_length=200)
    coeff = models.CharField(max_length=20)
    result = models.CharField(max_length=30)

    def finder(tournament):
        return Game.tournament == tournament

Django_part/one/views.py
from django.shortcuts import get_list_or_404
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Player, Game

def test(request):
    context = RequestContext(request, {})
    return render(request, 'one/test.html', context)


def about(request):
    return render(request, 'one/about.html')


class index_view(generic.ListView):
    template_name = 'one/index.html'
    # context_object_name = 'some_players'

    def get_queryset(self):
        return Player.objects.order_by('-total_games')[:10]


# def index(request):
#    players=Player.objects.order_by('name')
#    #template = loader.get_template('one/index.html')
#    context = RequestContext(request, {
#        'players': players,
#        })
#    #return HttpResponse(template.render(context))
#    return render(request,'one/index.html', context)
class predict_view(generic.ListView):
    template_name = 'one/predictions.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.order_by('-coeff')


#def predict(request):
#    #games=Game.objects.filter(time=player_name)
#    context = RequestContext(request, {})
#    #print (player_name)
#    return render(request,'one/predictions.html',context)
def strategy(request):
    context = RequestContext(request, {})
    return render(request, 'one/strategy.html', context)


def predict_search(request):
    if 'SearchByName' in request.GET:
        name = request.GET['SearchByName']
        message = "Имя:   %r" % name
        name = name.split(" ")
        print(name)
        player = Player.objects.filter(name=name)
    else:
        player = 'Not found'
    #return HttpResponse(message)
    context = RequestContext(request, {'player': player, })
    return render(request, 'one/SearchByName.html', context)


def variants(request):
    return render(request, 'one/variants.html')


def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

Django_part/one/templates/index.html
<head>
  <link href="styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="js/jquery1.9.1.min.js"></script>

</head>
<body>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
{% if players %}
    <ul>
        <table class="table table-bordered">
            <tr>
                <td>Имя</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td> <td>СПП по своим подачам</td> <td>СПП по чужим подачам</td> <td>СПП по сетам</td>  <td>Количество брейкпоинтов</td>
            </tr>
            {% for player in players %}
            <tr>
                <td>{{player.name}}</td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td> <td>{{player.svoi_podachi}}</td> <td>{{player.chuz_podachi}}</td> <td>{{player.set_rate}}</td> <td>{{player.break_point}}</td>
            </tr>
            {% endfor %}
        </table>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<script type="text/javascript" src="js/bootstrap.min.js"></script>
</body>

Django_part/one/templates/index/SearchByName.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Search in DB by name</title>
    <link href="styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="js/jquery1.9.1.min.js"></script>
</head>
<body>
{% if player %}
    <ul>
        <table class="table table-bordered">
            <tr>
                <td>Имя</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td> <td>СПП по своим подачам</td> <td>СПП по чужим подачам</td> <td>СПП по сетам</td>  <td>Количество брейкпоинтов</td>
            </tr>
            <tr>
                {% for player in player %}
                    <td>{{player.name}}</td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td> <td>{{player.svoi_podachi}}</td> <td>{{player.chuz_podachi}}</td> <td>{{player.set_rate}}</td> <td>{{player.break_point}}</td>
                {% endfor %}
            </tr>
        </table>
    </ul>
{% else %}
    <p>Not worked</p>
{% endif %}
</body>
</html>

Django_part/one/templates/index/index.html
<head>
  <link href="C:/Users/например Андрей/PycharmProjects/untitled4/one/templates/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="C:/Users/например Андрей/PycharmProjects/untitled4/one/templates/js/jquery1.9.1.min.js"></script>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<form action="predictSearch/" method="GET">
      <input type="text" class="form-control" placeholder="Search for..." name="SearchByName">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>
</form>
{% if object_list %}
    <ul>
        <table class="table table-bordered">
            <tr>
                <td>Имя</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td> <td>СПП по своим подачам</td> <td>СПП по чужим подачам</td> <td>СПП по сетам</td>  <td>Количество брейкпоинтов</td>
            </tr>
            {% for player in player_list %}
            <tr>
                <td>{{player.name}}</td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td> <td>{{player.svoi_podachi}}</td> <td>{{player.chuz_podachi}}</td> <td>{{player.set_rate}}</td> <td>{{player.break_point}}</td>
            </tr>
            {% endfor %}
        </table>
    </ul>
{% else %}
    <p>No players are available.</p>
{% endif %}
<script type="text/javascript" src="js/bootstrap.min.js"></script>
</body>

Django_part/one/templates/index/predictions.html
<head>
  <link href="styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="js/jquery1.9.1.min.js"></script>
    <h1>Predictions</h1>
</head>
<body>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<div class="row">
    <div class="col-lg-6">
    <form action="/search/" method="get">
      <input type="text" class="form-control" placeholder="Search for..." name="SearchByName">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </form>
  </div><!-- /.col-lg-6 -->
</div>
{% if player %}
    <ul>
        <table class="table table-bordered">
            <tr>
                <td>Имя</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td> <td>СПП по своим подачам</td> <td>СПП по чужим подачам</td> <td>СПП по сетам</td>  <td>Количество брейкпоинтов</td>
            </tr>
            <tr>
                {% for player in player %}
                    <td>{{player.name}}</td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td> <td>{{player.svoi_podachi}}</td> <td>{{player.chuz_podachi}}</td> <td>{{player.set_rate}}</td> <td>{{player.break_point}}</td>
                {% endfor %}
            </tr>
        </table>
    </ul>
{% else %}
    <p>Not worked</p>
{% endif %}
<script type="text/javascript" src="js/bootstrap.min.js"></script>
</body>

Django_part/one/templates/index/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
    <title>Тестовая страница</title>

    <!-- Bootstrap -->
    <link href="../one/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Привет, мир!</h1>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../one/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../one/js/bootstrap.min.js"></script>
  </body>
</html>

Django_part/one/templates/one/SearchByName.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    {% load staticfiles %}
    <link href="{% static "one/test/starter-temlate.css"%}" rel="stylesheet">
    <title>Поиск игрока</title>

</head>
<body>
{% if player %}
    <ul>
        <table class="table table-bordered ">
            <tr>
                <td>Имя</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td> <td>СПП по своим подачам</td> <td>СПП по чужим подачам</td> <td>СПП по сетам</td>  <td>Количество брейкпоинтов</td>
            </tr>
            <tr>
                {% for player in player %}
                    <td>{{player.name}}</td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td> <td>{{player.svoi_podachi}}</td> <td>{{player.chuz_podachi}}</td> <td>{{player.set_rate}}</td> <td>{{player.break_point}}</td>
                {% endfor %}
            </tr>
        </table>
    </ul>
{% else %}
    <p>Not worked</p>
{% endif %}
</body>
</html>

Django_part/one/templates/one/about.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {%  load staticfiles %}
    <link href="{% static "one/test/starter-temlate.css"%}" rel="stylesheet">
    <title>Про проект</title>
</head>
<body>
<div id="about">
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Задачи сайта</h2>
          <p>Ведение статистики по игрокам. Прогноз на игры. Создание стратегий для ставок. </p>
          <p><a class="btn btn-default" href='../' role="button">Перейти на главную страницу &raquo;</a></p>
        </div>
      </div>
    </div> <!


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
</div>
</body>
</html>

Django_part/one/templates/one/index.html
<head>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    {% load staticfiles %}
    <link href="{% static "one/test/starter-temlate.css"%}" rel="stylesheet">
    <title>Теннис</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" name="about" onclick="goAbout()">Проект большой теннис</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="">Главная</a></li>
            <li class="active"><a href="predictions/">Прогнозы</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div id="content">
      <div class="container">
        <h1>Сайт про ставки</h1>
        <p>Здесь надо что-то такое написать</p>
        <p><a class="btn btn-primary btn-lg" href="about" role="button">Проект большой теннис &raquo;</a></p>
      </div>
<table class="table">
    <tr>
        <td>
            <div class="side-rows">
                <p><img src="{% static "one/image/poststamp.jpg" %}" alt="Image doesn't work" width="200"></p>
            </div>
        </td>
        <td>
            <p class="lead">Это таблица игроков.</p>
            <form action="predict_search/" method="GET">
                    <input type="text" class="form-control" placeholder="Найти игрока" name="SearchByName">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Поиск</button>
                    </span>
            </form>
            {% if object_list %}
                <ul>
                <table class="table table-bordered">
                    <tr>
                        <span>
                        <td>Имя (есть ли возможность сделать ссылки без хардкода)</td> <td>Количество игр</td> <td>Соотношение побед к поражениям</td>
                        </span>
                    </tr>
                    {% for player in player_list %}
                    <tr>
                        <td><a href="predict_search/?SearchByName={{player.name}}">{{player.name}}</a></td> <td>{{player.total_games}}</td> <td>{{player.win_rate}}</td>
                    </tr>
                    {% endfor %}
                </table>
    </ul>
{% else %}
    <p>No players are available.</p>
{% endif %}
        </td>
        <td>
            <div class="side-rows">
                <p><img src="{% static "one/image/Tenniscourt.png" %}" alt="Image doesn't work" width="200"></p>
            </div>
        </td>
    </tr>
</table>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static "one/js/predict.js" %}"></script>
</body>

Django_part/one/templates/one/predictions.html
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    {% load staticfiles %}

    <!-- Custom styles for this template -->
    <link href="{% static "one/test/starter-temlate.css"%}" rel="stylesheet">
    <title>Прогнозы</title>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" name="about" onclick="goAboutFromPredictions()">Проект большой теннис</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="../">Главная</a></li>
            <li class="active"><a href="../predictions/">Прогнозы</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>
<div id="content">
<div id="strategy" class="starter-template">
<div class="btn-group starter-template" data-toggle="buttons">
  <label class="btn btn-primary">
    <input type="radio" name="options" id="strategy1" autocomplete="off">Все игры
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="strategy2" autocomplete="off">Ставки на победителя
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="strategy3" autocomplete="off">Стратегия 3
  </label>
</div>
</div>
<div id="gameTable">
<div id='predict'>
{% if game_list  %}
        <ul>
        <table class="table table-borded">
           <tr>
               <td>Турнир</td> <td>Участники</td> <td>Время</td> <td>Коэффициенты</td>
           </tr>
               {% for game in game_list %}
               <tr>
               <div id="gameTable">
               <td>{{ game.tournament }}</td> <td>{{ game.players }}</td> <td>{{ game.time }}</td> <td>{{ game.coeff }}</td>
               </div>
               </tr>
               {% endfor %}
        </table>
        </ul>
{% else %}
        <p>No more games for you</p>
{% endif %}
</div>

</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static "one/js/predict.js" %}"></script>
</body>

Django_part/one/templates/one/variants.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <title></title>
</head>
<body>
<div id="strategy1">
    <table class="table table-borded">
           <tr>
               <td>Турнир</td> <td>Участники</td> <td>Время</td> <td>Коэффициенты</td>
           </tr>
           <tr>
                <td>strategy1</td> <td>strategy1</td> <td>strategy1</td> <td>strategy1</td>
           </tr>
    </table>
</div>
<div id="strategy2"><tr><td>strategy2</td> <td>strategy2</td> <td>strategy2</td> <td>strategy2</td></tr></div>
<div id="strategy3"><tr><td>strategy3</td> <td>strategy3</td> <td>strategy3</td> <td>strategy3</td></tr></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

</body>
</html>